### ISSUE TITLE
add coverage report for each PR

### ISSUE THREAD

**Issue by mommermi** [NASA-Planetary-Science/sbpy#183]
This should not be an issue, but we will have to include remote tests to get a reasonable estimate of the coverage.

@mkelley, of all the remote tests we have, only two fail and both are part of `sbpy.spectroscopy.sun`:
* sbpy/spectroscopy/sun/tests/test_sun.py::TestSun::test_kurucz_nan_error FAILED
* sbpy/spectroscopy/sun/tests/test_sun.py::Test_default_sun::test_set_string_remote[Kurucz1993-source0] FAILED

Could you please have a look at those?

**Comment by mkelley** [comment]
How did you get sbpy/data/tests/test_orbit_remote.py to pass?  I'm failing locally :(

Something to do with the epochs.  But Ephem.from_horizons with the same values works:

```
>>> Orbit.from_horizons('Ceres', epochs={'start': "2018-01-02", 'stop': "2018-01-05", 'step': "6h"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/disks/data0/astro/Projects/sbpy/sbpy/data/orbit.py", line 123, in from_horizons
    elem = obj.elements(**kwargs)
  File "/home/msk/local/lib/python3.6/site-packages/astroquery-0.3.10.dev5220-py3.6.egg/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/home/msk/local/lib/python3.6/site-packages/astroquery-0.3.10.dev5220-py3.6.egg/astroquery/utils/process_asyncs.py", line 29, in newmethod
    result = self._parse_result(response, verbose=verbose)
  File "/home/msk/local/lib/python3.6/site-packages/astroquery-0.3.10.dev5220-py3.6.egg/astroquery/jplhorizons/core.py", line 1251, in _parse_result
    data = self._parse_horizons(response.text)
  File "/home/msk/local/lib/python3.6/site-packages/astroquery-0.3.10.dev5220-py3.6.egg/astroquery/jplhorizons/core.py", line 1145, in _parse_horizons
    raise ValueError(('Query failed without error message; '
ValueError: Query failed without error message; check URI for more information
```

```
>>> import pdb
>>> pdb.pm()
> /home/msk/local/lib/python3.6/site-packages/astroquery-0.3.10.dev5220-py3.6.egg/astroquery/jplhorizons/core.py(1145)_parse_horizons()
-> raise ValueError(('Query failed without error message; '
(Pdb) u
> /home/msk/local/lib/python3.6/site-packages/astroquery-0.3.10.dev5220-py3.6.egg/astroquery/jplhorizons/core.py(1251)_parse_result()
-> data = self._parse_horizons(response.text)
(Pdb) print(response.text)
*******************************************************************************
JPL/HORIZONS                       1 Ceres                 2019-Jul-11 15:59:56
Rec #:       1 (+COV) Soln.date: 2019-Jun-05_16:22:15   # obs: 1002 (1995-2019)
 
IAU76/J2000 helio. ecliptic osc. elements (au, days, deg., period=Julian yrs):
 
  EPOCH=  2454033.5 ! 2006-Oct-25.00 (TDB)         Residual RMS= .22345
   EC= .07987906346370539  QR= 2.544709153978707   TP= 2453193.6614275328
   OM= 80.40846590069125   W=  73.1893463033331    IN= 10.58671483589909
   A= 2.76562466186023     MA= 179.9741090118086   ADIST= 2.986540169741752
   PER= 4.59937            N= .214296068           ANGMOM= .028515965
   DAN= 2.68593            DDN= 2.81296            L= 153.3235262
   B= 10.1294158           MOID= 1.57962           TP= 2004-Jul-07.1614275328
 
Asteroid physical parameters (km, seconds, rotational period in hours):
   GM= 62.6284             RAD= 469.7              ROTPER= 9.07417
   H= 3.34                 G= .120                 B-V= .713
                           ALBEDO= .090            STYP= C
 
ASTEROID comments: 
1: soln ref.= JPL#46, OCC=0           radar(60 delay, 0 Dop.)
2: source=ORB
*******************************************************************************
 
Cannot interpret date. Type "?!" or try YYYY-Mon-Dy {HH:MM} format.

!$$SOF
TABLE_TYPE = ELEMENTS
MAKE_EPHEM = YES
OUT_UNITS = AU-D
COMMAND = "Ceres;"
CENTER = '500@10'
CSV_FORMAT = YES
ELEM_LABELS = YES
OBJ_DATA = YES
REF_SYSTEM = J2000
REF_PLANE = ECLIPTIC
TP_TYPE = ABSOLUTE
START_TIME = "'2018-01-02'"
STOP_TIME = "'2018-01-05'"
STEP_SIZE = "'6h'"
```



```
Full Python Version: 
3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.14.5
Scipy: 0.19.1
Matplotlib: 2.2.2
Pandas: 0.22.0
Astropy: 3.1.1
astroquery: 0.3.10.dev5517
astropy_helpers: 2.0.2
Using Astropy options: remote_data: any.

```

**Comment by mommermi** [comment]
update `astroquery`. I fixed that issue and it's already merged there.

**Comment by mkelley** [comment]
Ah, I had a problem installing it that I missed.  It works now.

**Comment by mkelley** [comment]
Skipping those tests for now, cf. #186, #188 .
