### ISSUE TITLE
Ephem.from_oo expects Tp_jd

### ISSUE THREAD

**Issue by mkelley** [NASA-Planetary-Science/sbpy#265]
**High-level problem description**
Propagating an orbit retrieved from the Minor Planet Center does not "just work."

**What did you do?**
```
from astropy.time import Time
from sbpy.data import Orbit, Ephem
orbit = Orbit.from_mpc('C/2017 K2')
eph = Ephem.from_oo(orbit, epochs=Time('2018-01-01'))
```

**What did you expect?**
The ephemeris to be generated.

**What did really happen?**
Crash!
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/msk/.venv/lib/python3.8/site-packages/sbpy-0.3.dev1077-py3.8.egg/sbpy/bib/core.py", line 171, in wrapper
    result = f(*args, **kwargs)
  File "/home/msk/.venv/lib/python3.8/site-packages/sbpy-0.3.dev1077-py3.8.egg/sbpy/data/ephem.py", line 761, in from_oo
    orb._to_oo(),
  File "/home/msk/.venv/lib/python3.8/site-packages/sbpy-0.3.dev1077-py3.8.egg/sbpy/data/orbit.py", line 363, in _to_oo
    (self['Tp_jd'].to('d').value -
  File "/home/msk/.venv/lib/python3.8/site-packages/sbpy-0.3.dev1077-py3.8.egg/sbpy/data/core.py", line 637, in __getitem__
    ident = self._translate_columns(ident)[0]
  File "/home/msk/.venv/lib/python3.8/site-packages/sbpy-0.3.dev1077-py3.8.egg/sbpy/data/core.py", line 672, in _translate_columns
    raise KeyError('field {:s} not available.'.format(
KeyError: 'field Tp_jd not available.'
```

However, Tp is included in the orbit under a different key name.  Best approach would be we look for Tp as a `Time` object, rather than a field name Tp_jd.

**Provide information on your environment:**
operating system and version: Linux
sbpy version: 0.3.dev1077
astropy version: 4.0.1.post1
numpy version: 1.18.5

**Comment by mkelley** [comment]
```
from astropy.time import Time
from sbpy.data import Orbit, Ephem
orbit = Orbit.from_mpc('C/2017 K2')
orbit['H'] = 5 * u.mag
orbit['G'] = 0.15
eph = Ephem.from_oo(orbit, epochs=Time('2018-01-01'))
```

Works now via updates in #262
